---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # Fill Cassandra tables
  - command: kubectl exec -ti cassandra-e2e-dc1-rack1-1 --namespace $NAMESPACE  -- /opt/cassandra/tools/bin/cassandra-stress write n=20000 cl=one -rate threads=1 -mode native cql3 user=cassandra password=cassandra -schema 'Keyspace=k1 replication(strategy=NetworkTopologyStrategy, dc1=2)'
  #- command: kubectl exec -ti cassandra-e2e-dc1-rack1-1 --namespace $NAMESPACE -- cqlsh -u cassandra -p cassandra --no-color -k k1 -e "select count(*) from standard1"|grep count -A2
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraBackup
metadata:
  name: test-cassandra-backup
  annotations:
    avoid-temp: annotation-nil-map
spec:
  cassandraCluster: cassandra-e2e
  datacenter: dc1
  storageLocation: "s3://casskop-backup-restore-test"
  snapshotTag: kuttlTestBackup
  secret: gcs-s3-backup-restore-secret
  entities: k1.standard1
  rename:
      k1.standard1: k1.standard2
