apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # First uninstall previous (potential) CRs left in NS
  - command: kubectl delete cassandraclusters.db.orange.com --all
    ignoreFailure: true
    namespaced: true

  - command: kubectl delete cassandrabackups.db.orange.com --all
    ignoreFailure: true
    namespaced: true

  - command: kubectl delete cassandrarestores.db.orange.com --all
    ignoreFailure: true
    namespaced: true

 # Then delete Casskop helm installation (needed because Kuttl in single given NS does not remove all resources created by swipping the NS)
  - command: helm uninstall casskop $helm_name/$chart_name
    ignoreFailure: true
    namespaced: true

 # Install Rickaastley requirements (network policies, configmap cacert) to run Casskop
  - command: kubectl apply -f ../../rickaastley-specific-config
    namespaced: true

  # Apply S3 secret
  - command: ()../../rickaastley-specific-config/secret-s3.yaml.sh) | kubectl apply -f -
    namespaced: true


 # Finally, install Casskop chart (from Artifactory) & override the default Casskop docker image with an internal one from Artifactory (same as default)
  - command: helm install casskop $helm_name/$chart_name --skip-crds --set image.repository=ext-dockerio.artifactory.si.francetelecom.fr/orangeopensource/casskop --set image.tag=v1.0.2-release --no-hooks --set debug.enabled=true
    namespaced: true

---

apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
spec:
  nodesPerRacks: 2
  cassandraImage: ext-dockerio.artifactory.si.francetelecom.fr/cassandra:latest
  dataCapacity: "1Gi"
  dataStorageClass: local-storage
  gcStdout: true
  initContainerImage: ext-dockerio.artifactory.si.francetelecom.fr/cassandra:latest
  maxPodUnavailable: 1
#  pod:
#    annotations:
#      cni.projectcalico.org/ipv4pools: '["pns-cassandra-preprod-routable"]'
  readOnlyRootFilesystem: true
  hardAntiAffinity: false
  deletePVC: true
  autoPilot: true
  autoUpdateSeedList: false
  restartCountBeforePodDeletion: 3
  runAsUser: 999
  bootstrapImage: ext-dockerio.artifactory.si.francetelecom.fr/orangeopensource/cassandra-bootstrap:0.1.7
  backRestSidecar:
    image: sdfy-aic-casskop-docker.artifactory.si.francetelecom.fr/instaclustr-icarus:1.0.5
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  resources:
    requests: &requests
      cpu: 500m
      memory: 512Mi
    limits: *requests
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1