apiVersion: db.orange.com/v1alpha1
kind: CassandraBackup
metadata:
  name: test-cassandra-backup
  namespace: casskop-cassandra-e2e
  labels:
    app: cassandra
spec:
  cassandraCluster: cassandra-e2e
  datacenter: dc1
  storageLocation: "s3://casskop-backup-restore-test"
  snapshotTag: kuttlTestBackup
  secret: rick-s3-backup-restore-secret
  entities: k1.standard1
