apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # First uninstall previous (potential) Casskop installation (needed because Kuttl in single given NS does not remove all resources created by swipping the NS)
  - command: helm delete casskop --namespace casskop-cassandra-e2e $helm_name/$chart_name --purge
    ignoreFailure: true
  # Install Casskop local chart & override the casskop image with an internal one (clone)
  - command: helm install casskop --namespace casskop-cassandra-e2e $helm_name/$chart_name --skip-crds --set image.repository=ext-dockerio.artifactory.si.francetelecom.fr/orangeopensource/casskop --set image.tag=v1.0.2-release --no-hooks --set debug.enabled=true
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
  namespace: casskop-cassandra-e2e
spec:
  nodesPerRacks: 1
  cassandraImage: pfs-pns3-registry.artifactory.si.francetelecom.fr/k8s/cassandra-k8s:3.11.3-1915107
  dataCapacity: "1Gi"
  hardAntiAffinity: false
  deletePVC: false
  autoPilot: true
  autoUpdateSeedList: false
  bootstrapImage: pfs-pns3-registry.artifactory.si.francetelecom.fr/k8s/cassandra-bootstrap:0.1.4-2331979
  backRestSidecar:
    image: pfs-pns3-registry.artifactory.si.francetelecom.fr/k8s/instaclustr-icarus:icarus-1.0.5
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  resources:
    requests: &requests
      cpu: 100m
      memory: 512Mi
    limits: *requests
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1