apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: helm install casskop --namespace=casskop-cassandra-e2e orange-incubator/cassandra-operator
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
  namespace: casskop-cassandra-e2e
spec:
  nodesPerRacks: 1
  cassandraImage: cassandra:latest
  dataCapacity: "1Gi"
  hardAntiAffinity: false
  deletePVC: false
  autoPilot: true
  autoUpdateSeedList: false
  bootstrapImage: orangeopensource/cassandra-bootstrap:0.1.7
  resources:
    requests: &requests
      cpu: 100m
      memory: 512Mi
    limits: *requests
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1