apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
  namespace: casskop-cassandra-e2e
spec:
  nodesPerRacks: 1
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 2
        rack:
          - name: rack1