apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 500
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-e2e-dc1-rack1
status:
  currentReplicas: 1
  replicas: 1
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
spec:
  nodesPerRacks: 1
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        rack:
          - name: rack1
status:
  cassandraRackStatus:
    dc1-rack1:
      cassandraLastAction:
        name: ScaleDown
        status: Done