apiVersion: db.orange.com/v1alpha1
kind: CassandraBackup
metadata:
  name: test-cassandra-backup
  namespace: casskop-cassandra-e2e
  labels:
    app: cassandra
spec:
  cassandraCluster: cassandra-e2e
  datacenter: dc1
  storageLocation: s3://cassie
  snapshotTag: SnapshotTag2
  secret: rick-s3-backup-restore-secrets
#  schedule: "@midnight"
  entities: k1.t1,k2.t3